"""add products table

Revision ID: 3ca1ab8ab71a
Revises: e7aa9ef03b03
Create Date: 2024-10-24 22:51:04.824628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ca1ab8ab71a'
down_revision: Union[str, None] = 'e7aa9ef03b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
